# Sources
tap "homebrew/bundle"
tap "homebrew/core"

brew "bats"
brew "coreutils"

# Utilities
brew "stow"
brew "tree"
# brew "mackup"
brew "make"
brew "composer"
brew "mas"
brew "php"
brew "yarn", args: ["without-node"]
brew "coda-cli"
brew "wp-cli"
brew "mariadb"
brew "exiftool"
brew "libdvdcss"
# ffmpeg, args: ["with-libvpx"]
# imagemagick , args: ["with-webp"]
# wget
# hub
# hugo
# tig
# asciinema
# rbenv
